backend:
name: github
repo: ojanpohja/desing-dev-integration
branch: main
# NOTE: For production editing on GitHub Pages, you need a GitHub OAuth app / proxy.
# For local development you can enable the local backend below.


# Uncomment for local dev: run `npx decap-server` and visit http://localhost:4321/admin
# local_backend: true


publish_mode: editorial_workflow
media_folder: "public/images/uploads" # where files are stored in repo
public_folder: "/images/uploads" # how files are referenced in the site


collections:
- name: "pages"
label: "Pages"
files:
- file: "content/pages/home.md"
label: "Home"
name: "home"
fields:
- { label: Title, name: title, widget: string }
- { label: Summary, name: summary, widget: string, required: false }
- { label: Body, name: body, widget: markdown }
- file: "content/pages/about.md"
label: "About"
name: "about"
fields:
- { label: Title, name: title, widget: string }
- { label: Body, name: body, widget: markdown }


- name: "projects"
label: "Projects"
folder: "content/projects"
create: true
slug: "{{slug}}"
fields:
- { label: Title, name: title, widget: string }
- { label: Date, name: date, widget: datetime, time_format: false }
- { label: Summary, name: summary, widget: text, required: false }
- { label: Cover Image, name: cover, widget: image, required: false }
- { label: Tags, name: tags, widget: list, required: false }
- { label: Body, name: body, widget: markdown }